Resources:
  TestEFS:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      AvailabilityZoneName : "us-east-1a"

  TestEFSAP:
    Type: 'AWS::EFS::AccessPoint'  
    Properties:
      FileSystemId: !Ref TestEFS
      RootDirectory: 
        Path: "/testpath/test"